services:
  onthespot-webui:
    image: onthespot-webui:latest
    build: .
    container_name: onthespot-webui
    restart: unless-stopped
    ports:
      - "6767:6767"
    volumes:
      - /Users/Shared/NAS/music:/root/Music/OnTheSpot
      - ./Videos:/root/Videos/OnTheSpot
      - ./Config:/root/.config/onthespot
