services:
  onthespot-api:
    build: .
    container_name: onthespot-api
    restart: unless-stopped
    ports:
      - "6767:6767"
    volumes:
      - ./Music:/root/Music/OnTheSpot
      - ./Videos:/root/Videos/OnTheSpot
      - ./Config:/root/.config/onthespot
