export type TranslationKey =
  | "workspace" | "manage" | "search_discover" | "local_library"
  | "playlist_sorting" | "download_queue" | "download_statistics" | "accounts"
  | "diagnostics" | "notification_history" | "server_logs" | "settings"
  | "edit_navigation" | "done_editing" | "dark_mode" | "light_mode" | "edit_sections"
  | "application_language" | "save" | "cancel" | "search" | "download" | "queued"
  | "add_account" | "remove" | "connected" | "inactive";

type TranslationPack = Partial<Record<TranslationKey, string>>;

const TRANSLATIONS: Record<string, TranslationPack> = {
  de_DE: { workspace: "Arbeitsbereich", manage: "Verwalten", search_discover: "Suchen & entdecken", local_library: "Lokale Bibliothek", playlist_sorting: "Playlist-Sortierung", download_queue: "Download-Warteschlange", download_statistics: "Download-Statistiken", accounts: "Konten", diagnostics: "Diagnose", notification_history: "Benachrichtigungsverlauf", server_logs: "Serverprotokolle", settings: "Einstellungen", edit_navigation: "Navigation bearbeiten", done_editing: "Bearbeitung beenden", dark_mode: "Dunkler Modus", light_mode: "Heller Modus", edit_sections: "Abschnitte bearbeiten", application_language: "Anwendungssprache", save: "Speichern", cancel: "Abbrechen", search: "Suchen", download: "Herunterladen", queued: "In Warteschlange", add_account: "Konto hinzufügen", remove: "Entfernen", connected: "Verbunden", inactive: "Inaktiv" },
  es_ES: { workspace: "Espacio de trabajo", manage: "Administrar", search_discover: "Buscar y descubrir", local_library: "Biblioteca local", playlist_sorting: "Ordenar listas", download_queue: "Cola de descargas", download_statistics: "Estadísticas de descargas", accounts: "Cuentas", diagnostics: "Diagnóstico", notification_history: "Historial de notificaciones", server_logs: "Registros del servidor", settings: "Configuración", edit_navigation: "Editar navegación", done_editing: "Terminar edición", dark_mode: "Modo oscuro", light_mode: "Modo claro", edit_sections: "Editar secciones", application_language: "Idioma de la aplicación", save: "Guardar", cancel: "Cancelar", search: "Buscar", download: "Descargar", queued: "En cola", add_account: "Añadir cuenta", remove: "Eliminar", connected: "Conectado", inactive: "Inactivo" },
  fr_FR: { workspace: "Espace de travail", manage: "Gérer", search_discover: "Rechercher et découvrir", local_library: "Bibliothèque locale", playlist_sorting: "Tri des playlists", download_queue: "File de téléchargement", download_statistics: "Statistiques de téléchargement", accounts: "Comptes", diagnostics: "Diagnostic", notification_history: "Historique des notifications", server_logs: "Journaux du serveur", settings: "Paramètres", edit_navigation: "Modifier la navigation", done_editing: "Terminer la modification", dark_mode: "Mode sombre", light_mode: "Mode clair", edit_sections: "Modifier les sections", application_language: "Langue de l’application", save: "Enregistrer", cancel: "Annuler", search: "Rechercher", download: "Télécharger", queued: "En file", add_account: "Ajouter un compte", remove: "Supprimer", connected: "Connecté", inactive: "Inactif" },
  it_IT: { workspace: "Area di lavoro", manage: "Gestisci", search_discover: "Cerca e scopri", local_library: "Libreria locale", playlist_sorting: "Ordinamento playlist", download_queue: "Coda di download", download_statistics: "Statistiche download", accounts: "Account", diagnostics: "Diagnostica", notification_history: "Cronologia notifiche", server_logs: "Log del server", settings: "Impostazioni", edit_navigation: "Modifica navigazione", done_editing: "Fine modifica", dark_mode: "Modalità scura", light_mode: "Modalità chiara", edit_sections: "Modifica sezioni", application_language: "Lingua dell'applicazione", save: "Salva", cancel: "Annulla", search: "Cerca", download: "Scarica", queued: "In coda", add_account: "Aggiungi account", remove: "Rimuovi", connected: "Connesso", inactive: "Inattivo" },
  ja_JP: { workspace: "ワークスペース", manage: "管理", search_discover: "検索・発見", local_library: "ローカルライブラリ", playlist_sorting: "プレイリストの並べ替え", download_queue: "ダウンロードキュー", download_statistics: "ダウンロード統計", accounts: "アカウント", diagnostics: "診断", notification_history: "通知履歴", server_logs: "サーバーログ", settings: "設定", edit_navigation: "ナビゲーションを編集", done_editing: "編集を完了", dark_mode: "ダークモード", light_mode: "ライトモード", edit_sections: "セクションを編集", application_language: "アプリの言語", save: "保存", cancel: "キャンセル", search: "検索", download: "ダウンロード", queued: "キューに追加済み", add_account: "アカウントを追加", remove: "削除", connected: "接続済み", inactive: "非アクティブ" },
  ko_KR: { workspace: "작업 공간", manage: "관리", search_discover: "검색 및 발견", local_library: "로컬 라이브러리", playlist_sorting: "재생목록 정렬", download_queue: "다운로드 대기열", download_statistics: "다운로드 통계", accounts: "계정", diagnostics: "진단", notification_history: "알림 기록", server_logs: "서버 로그", settings: "설정", edit_navigation: "탐색 편집", done_editing: "편집 완료", dark_mode: "다크 모드", light_mode: "라이트 모드", edit_sections: "섹션 편집", application_language: "애플리케이션 언어", save: "저장", cancel: "취소", search: "검색", download: "다운로드", queued: "대기열에 추가됨", add_account: "계정 추가", remove: "제거", connected: "연결됨", inactive: "비활성" },
  nl_NL: { workspace: "Werkruimte", manage: "Beheren", search_discover: "Zoeken en ontdekken", local_library: "Lokale bibliotheek", playlist_sorting: "Afspeellijsten sorteren", download_queue: "Downloadwachtrij", download_statistics: "Downloadstatistieken", accounts: "Accounts", diagnostics: "Diagnostiek", notification_history: "Meldingsgeschiedenis", server_logs: "Serverlogboeken", settings: "Instellingen", edit_navigation: "Navigatie bewerken", done_editing: "Bewerken afronden", dark_mode: "Donkere modus", light_mode: "Lichte modus", edit_sections: "Secties bewerken", application_language: "Applicatietaal", save: "Opslaan", cancel: "Annuleren", search: "Zoeken", download: "Downloaden", queued: "In wachtrij", add_account: "Account toevoegen", remove: "Verwijderen", connected: "Verbonden", inactive: "Inactief" },
  pl_PL: { workspace: "Obszar roboczy", manage: "Zarządzaj", search_discover: "Szukaj i odkrywaj", local_library: "Biblioteka lokalna", playlist_sorting: "Sortowanie playlist", download_queue: "Kolejka pobierania", download_statistics: "Statystyki pobierania", accounts: "Konta", diagnostics: "Diagnostyka", notification_history: "Historia powiadomień", server_logs: "Dzienniki serwera", settings: "Ustawienia", edit_navigation: "Edytuj nawigację", done_editing: "Zakończ edycję", dark_mode: "Tryb ciemny", light_mode: "Tryb jasny", edit_sections: "Edytuj sekcje", application_language: "Język aplikacji", save: "Zapisz", cancel: "Anuluj", search: "Szukaj", download: "Pobierz", queued: "W kolejce", add_account: "Dodaj konto", remove: "Usuń", connected: "Połączono", inactive: "Nieaktywne" },
  pt_BR: { workspace: "Área de trabalho", manage: "Gerenciar", search_discover: "Pesquisar e descobrir", local_library: "Biblioteca local", playlist_sorting: "Ordenação de playlists", download_queue: "Fila de downloads", download_statistics: "Estatísticas de downloads", accounts: "Contas", diagnostics: "Diagnóstico", notification_history: "Histórico de notificações", server_logs: "Logs do servidor", settings: "Configurações", edit_navigation: "Editar navegação", done_editing: "Concluir edição", dark_mode: "Modo escuro", light_mode: "Modo claro", edit_sections: "Editar seções", application_language: "Idioma do aplicativo", save: "Salvar", cancel: "Cancelar", search: "Pesquisar", download: "Baixar", queued: "Na fila", add_account: "Adicionar conta", remove: "Remover", connected: "Conectado", inactive: "Inativo" },
  pt_PT: { workspace: "Área de trabalho", manage: "Gerir", search_discover: "Pesquisar e descobrir", local_library: "Biblioteca local", playlist_sorting: "Ordenação de playlists", download_queue: "Fila de transferências", download_statistics: "Estatísticas de transferências", accounts: "Contas", diagnostics: "Diagnóstico", notification_history: "Histórico de notificações", server_logs: "Registos do servidor", settings: "Definições", edit_navigation: "Editar navegação", done_editing: "Concluir edição", dark_mode: "Modo escuro", light_mode: "Modo claro", edit_sections: "Editar secções", application_language: "Idioma da aplicação", save: "Guardar", cancel: "Cancelar", search: "Pesquisar", download: "Transferir", queued: "Na fila", add_account: "Adicionar conta", remove: "Remover", connected: "Ligado", inactive: "Inativo" },
  tr_TR: { workspace: "Çalışma alanı", manage: "Yönet", search_discover: "Ara ve keşfet", local_library: "Yerel kitaplık", playlist_sorting: "Çalma listesi sıralama", download_queue: "İndirme kuyruğu", download_statistics: "İndirme istatistikleri", accounts: "Hesaplar", diagnostics: "Tanılama", notification_history: "Bildirim geçmişi", server_logs: "Sunucu günlükleri", settings: "Ayarlar", edit_navigation: "Gezinmeyi düzenle", done_editing: "Düzenlemeyi bitir", dark_mode: "Koyu mod", light_mode: "Açık mod", edit_sections: "Bölümleri düzenle", application_language: "Uygulama dili", save: "Kaydet", cancel: "İptal", search: "Ara", download: "İndir", queued: "Kuyrukta", add_account: "Hesap ekle", remove: "Kaldır", connected: "Bağlı", inactive: "Etkin değil" },
  uk_UA: { workspace: "Робоча область", manage: "Керування", search_discover: "Пошук і огляд", local_library: "Локальна медіатека", playlist_sorting: "Сортування плейлистів", download_queue: "Черга завантажень", download_statistics: "Статистика завантажень", accounts: "Облікові записи", diagnostics: "Діагностика", notification_history: "Історія сповіщень", server_logs: "Журнали сервера", settings: "Налаштування", edit_navigation: "Редагувати навігацію", done_editing: "Завершити редагування", dark_mode: "Темний режим", light_mode: "Світлий режим", edit_sections: "Редагувати розділи", application_language: "Мова застосунку", save: "Зберегти", cancel: "Скасувати", search: "Пошук", download: "Завантажити", queued: "У черзі", add_account: "Додати обліковий запис", remove: "Видалити", connected: "Підключено", inactive: "Неактивний" },
  zh_CN: { workspace: "工作区", manage: "管理", search_discover: "搜索与发现", local_library: "本地音乐库", playlist_sorting: "播放列表排序", download_queue: "下载队列", download_statistics: "下载统计", accounts: "帐户", diagnostics: "诊断", notification_history: "通知历史", server_logs: "服务器日志", settings: "设置", edit_navigation: "编辑导航", done_editing: "完成编辑", dark_mode: "深色模式", light_mode: "浅色模式", edit_sections: "编辑部分", application_language: "应用语言", save: "保存", cancel: "取消", search: "搜索", download: "下载", queued: "已加入队列", add_account: "添加帐户", remove: "移除", connected: "已连接", inactive: "未启用" },
  zh_TW: { workspace: "工作區", manage: "管理", search_discover: "搜尋與探索", local_library: "本機媒體庫", playlist_sorting: "播放清單排序", download_queue: "下載佇列", download_statistics: "下載統計", accounts: "帳戶", diagnostics: "診斷", notification_history: "通知記錄", server_logs: "伺服器日誌", settings: "設定", edit_navigation: "編輯導覽", done_editing: "完成編輯", dark_mode: "深色模式", light_mode: "淺色模式", edit_sections: "編輯區段", application_language: "應用程式語言", save: "儲存", cancel: "取消", search: "搜尋", download: "下載", queued: "已加入佇列", add_account: "新增帳戶", remove: "移除", connected: "已連線", inactive: "未啟用" },
};

export const translate = (language: string | undefined, key: TranslationKey, fallback: string): string =>
  TRANSLATIONS[language || "en_US"]?.[key] || fallback;
