"""Run the OnTheSpot Spotify Connect companion on the Spotify user's LAN.

The companion keeps the ZeroConf/mDNS part local to the desktop or home LAN
and forwards only the short-lived pairing payload to the remote OnTheSpot API.
"""

from __future__ import annotations

import argparse
import ipaddress
import json
import os
import socket
import sys
import time
from pathlib import Path

import requests
import librespot.zeroconf as librespot_zeroconf
from librespot.zeroconf import ZeroconfServer


def choose_interface(configured: str | None) -> str | None:
    if configured:
        return configured.strip() or None
    try:
        candidates = socket.gethostbyname_ex(socket.gethostname())[2]
    except OSError:
        candidates = []
    usable: list[str] = []
    for value in candidates:
        try:
            address = ipaddress.ip_address(value)
        except ValueError:
            continue
        if not address.is_private or address.is_loopback or address.is_link_local:
            continue
        # Do not advertise common Docker/Hyper-V/Tailscale addresses when a
        # normal private LAN address is available.
        if str(address).startswith("172.17.") or str(address).startswith("192.168.56."):
            continue
        if address not in usable:
            usable.append(str(address))
    if usable:
        return next((value for value in usable if value.startswith("192.168.")), usable[0])

    probe = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        probe.connect(("8.8.8.8", 80))
        return probe.getsockname()[0]
    except OSError:
        return None
    finally:
        probe.close()


def create_server(name: str, port: int, state_file: Path, interface: str | None):
    ZeroconfServer._ZeroconfServer__default_get_info_fields["clientID"] = "65b708073fc0480ea92a077233ca87bd"
    builder = ZeroconfServer.Builder()
    builder.device_name = name
    builder.set_listen_port(port)
    builder.conf.stored_credentials_file = str(state_file)

    original_zeroconf = librespot_zeroconf.zeroconf.Zeroconf
    original_hostname = ZeroconfServer.get_useful_hostname
    if interface:
        librespot_zeroconf.zeroconf.Zeroconf = lambda *args, **kwargs: original_zeroconf(
            *args, interfaces=[interface], **kwargs
        )
        ZeroconfServer.get_useful_hostname = lambda self: interface
    try:
        return builder.create()
    finally:
        librespot_zeroconf.zeroconf.Zeroconf = original_zeroconf
        ZeroconfServer.get_useful_hostname = original_hostname


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run the OnTheSpot Spotify Connect companion")
    parser.add_argument("--server-url", required=True, help="HTTPS/Tailscale URL of the remote OnTheSpot server")
    parser.add_argument("--pairing-token", required=True, help="One-time token generated by Playlist Sorting")
    parser.add_argument("--interface", help="LAN IPv4 address to advertise; auto-detected by default")
    parser.add_argument("--port", type=int, default=6768, help="Local Spotify Connect HTTP port")
    parser.add_argument("--name", default="OnTheSpot Companion", help="Name shown in Spotify Connect")
    parser.add_argument(
        "--state-file",
        default="",
        help="Local credential state path; defaults to the user's OnTheSpot companion directory",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    server_url = args.server_url.rstrip("/")
    state_file = Path(args.state_file).expanduser() if args.state_file else Path.home() / ".onthespot" / "companion" / "spotify_connect_login.json"
    state_file.parent.mkdir(parents=True, exist_ok=True)
    try:
        state_file.unlink()
    except FileNotFoundError:
        pass

    interface = choose_interface(args.interface)
    print(f"Starting {args.name} on {interface or 'all local interfaces'}:{args.port}", flush=True)
    print("Open Spotify → Connect to a device and select the companion.", flush=True)
    try:
        server = create_server(args.name, args.port, state_file, interface)
    except Exception as exc:
        print(f"Could not start Spotify Connect discovery: {exc}", file=sys.stderr, flush=True)
        return 1

    try:
        while not server.has_valid_session():
            time.sleep(1)
        deadline = time.time() + 10
        while not state_file.is_file() and time.time() < deadline:
            time.sleep(0.25)
        if not state_file.is_file():
            print("Spotify connected, but no login payload was written.", file=sys.stderr, flush=True)
            return 1
        with state_file.open("r", encoding="utf-8") as handle:
            login = json.load(handle)
        response = requests.post(
            f"{server_url}/accounts/spotify/companion/complete",
            json={"pairing_token": args.pairing_token, "login": login},
            timeout=30,
        )
        if not response.ok:
            print(f"OnTheSpot rejected the companion login: {response.text}", file=sys.stderr, flush=True)
            return 1
        print("Spotify account delivered to OnTheSpot successfully.", flush=True)
        return 0
    except KeyboardInterrupt:
        print("Stopped.", flush=True)
        return 130
    except (OSError, ValueError, requests.RequestException) as exc:
        print(f"Companion failed: {exc}", file=sys.stderr, flush=True)
        return 1
    finally:
        try:
            server.close_session()
        except Exception:
            pass
        try:
            server.close()
        except Exception:
            pass


if __name__ == "__main__":
    raise SystemExit(main())
